const GradeWriteType = {
    DOWNLOAD_STUDENT_LIST_TEMPLATE: 'DOWNLOAD_TEMPLATE_STUDENT_LIST',
    UPLOAD_STUDENT_LIST: 'UPLOAD_STUDENT_LIST',

    DOWNLOAD_STUDENT_GRADE_BOARD: 'DOWNLOAD_STUDENT_GRADE_BOARD',
    UPLOAD_STUDENT_GRADE_BOARD: 'UPLOAD_STUDENT_GRADE_BOARD',

    DOWNLOAD_SPEC_GRADE_TEMPLATE: 'DOWNLOAD_STUDENT_SPEC_GRADE',
    UPLOAD_SPEC_GRADE: 'UPLOAD_STUDENT_SPEC_GRADE',
}

module.exports = GradeWriteType